spring.application.name=hospitalManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB
spring.datasource.username=postgres
spring.datasource.password=99ookkmm
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

server.servlet.context-path=/api/v1

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

##security config
#spring.security.user.name=shivam
#spring.security.user.password=pass123

jwt.secretKey=kwejfjqgfoasgjioqwjiorjgtioqrwit398302903uerngqior0932jtvsnvpoq

spring.config.import=optional:application-secret.properties

spring.security.oauth2.client.registration.github.client-id=Ov23lida9NnNcr7b3Kf6
spring.security.oauth2.client.registration.github.client-secret=c2a44e6a0f5f16629532a6b12ebda6e91ab4ed53

